In [1]:
import pandas as pd
import matplotlib as plt
from pathlib import Path

In [2]:

import os

project_root = os.getcwd()
if not os.path.exists(os.path.join(project_root, "data", "ethiopia_fi_unified_data.csv")):
    project_root = os.path.dirname(project_root)

csv_path = os.path.join(project_root, "data", "ethiopia_fi_unified_data.csv")
df = pd.read_csv(csv_path)

In [3]:
project_root = os.getcwd()
if not os.path.exists(os.path.join(project_root, "data", "reference_codes.csv")):
    project_root = os.path.dirname(project_root)

csv_path = os.path.join(project_root, "data", "reference_codes.csv")
ref_df = pd.read_csv(csv_path)

In [4]:
df.head()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [5]:
df.columns

Index(['record_id', 'record_type', 'category', 'pillar', 'indicator',
       'indicator_code', 'indicator_direction', 'value_numeric', 'value_text',
       'value_type', 'unit', 'observation_date', 'period_start', 'period_end',
       'fiscal_year', 'gender', 'location', 'region', 'source_name',
       'source_type', 'source_url', 'confidence', 'related_indicator',
       'relationship_type', 'impact_direction', 'impact_magnitude',
       'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country',
       'collected_by', 'collection_date', 'original_text', 'notes'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43 entries, 0 to 42
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   record_id            43 non-null     str
 1   record_type          43 non-null     str
 2   category             10 non-null     str
 3   pillar               33 non-null     str
 4   indicator            43 non-null     str
 5   indicator_code       43 non-null     str
 6   indicator_direction  33 non-null     str
 7   value_numeric        33 non-null     float64
 8   value_text           10 non-null     str
 9   value_type           43 non-null     str
 10  unit                 33 non-null     str
 11  observation_date     43 non-null     str
 12  period_start         10 non-null     str
 13  period_end           10 non-null     str
 14  fiscal_year          43 non-null     str
 15  gender               43 non-null     str
 16  location             43 non-null     str
 17  region               0 non-null      float64
 18  source_name          43 non-null     str
 19  source_type          43 non-null     str
 20  source_url           31 non-null     str
 21  confidence           43 non-null     str
 22  related_indicator    0 non-null      float64
 23  relationship_type    0 non-null      float64
 24  impact_direction     0 non-null      float64
 25  impact_magnitude     0 non-null      float64
 26  impact_estimate      0 non-null      float64
 27  lag_months           0 non-null      float64
 28  evidence_basis       0 non-null      float64
 29  comparable_country   43 non-null     str
 30  collected_by         43 non-null     str
 31  collection_date      10 non-null     str
 32  original_text        33 non-null     str
 33  notes                0 non-null      float64
dtypes: float64(10), str(24)
memory usage: 11.6 KB

In [7]:
df.isnull().sum()

record_id               0
record_type             0
category               33
pillar                 10
indicator               0
indicator_code          0
indicator_direction    10
value_numeric          10
value_text             33
value_type              0
unit                   10
observation_date        0
period_start           33
period_end             33
fiscal_year             0
gender                  0
location                0
region                 43
source_name             0
source_type             0
source_url             12
confidence              0
related_indicator      43
relationship_type      43
impact_direction       43
impact_magnitude       43
impact_estimate        43
lag_months             43
evidence_basis         43
comparable_country      0
collected_by            0
collection_date        33
original_text          10
notes                  43
dtype: int64

In [8]:
ref_df.columns
ref_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   field        71 non-null     str
 1   code         71 non-null     str
 2   description  71 non-null     str
 3   applies_to   71 non-null     str
dtypes: str(4)
memory usage: 2.3 KB

In [9]:
ref_df.isnull().sum()
ref_df.head()

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All

In [10]:
df["record_type"].value_counts()

record_type
observation    30
event          10
target          3
Name: count, dtype: int64

In [11]:
df["pillar"].value_counts(dropna=False)

pillar
ACCESS           16
USAGE            11
NaN              10
GENDER            5
AFFORDABILITY     1
Name: count, dtype: int64

In [12]:
df["source_type"].value_counts()

source_type
operator      15
survey        10
regulator      7
research       4
policy         3
calculated     2
news           2
Name: count, dtype: int64

In [13]:
df["confidence"].value_counts()

confidence
high      40
medium     3
Name: count, dtype: int64

In [14]:
df["indicator_code"].value_counts()

indicator_code
ACC_OWNERSHIP         7
ACC_FAYDA             4
ACC_MM_ACCOUNT        2
ACC_4G_COV            2
USG_P2P_COUNT         2
GEN_GAP_ACC           2
GEN_MM_SHARE          2
ACC_MOBILE_PEN        1
USG_P2P_VALUE         1
USG_ATM_COUNT         1
USG_ATM_VALUE         1
USG_CROSSOVER         1
USG_TELEBIRR_USERS    1
USG_TELEBIRR_VALUE    1
USG_MPESA_USERS       1
USG_MPESA_ACTIVE      1
USG_ACTIVE_RATE       1
AFF_DATA_INCOME       1
GEN_GAP_MOBILE        1
EVT_TELEBIRR          1
EVT_SAFARICOM         1
EVT_MPESA             1
EVT_FAYDA             1
EVT_FX_REFORM         1
EVT_CROSSOVER         1
EVT_MPESA_INTEROP     1
EVT_ETHIOPAY          1
EVT_NFIS2             1
EVT_SAFCOM_PRICE      1
Name: count, dtype: int64

In [15]:
df["observation_date"] = pd.to_datetime(df["observation_date"])

In [16]:
print(df["observation_date"].min())
print(df["observation_date"].max())

2014-12-31 00:00:00
2030-12-31 00:00:00

In [17]:
events = df[df["record_type"] == "event"]

In [18]:
events[["observation_date","indicator","category"]].sort_values("observation_date")

   observation_date                               indicator        category
33       2021-05-17                         Telebirr Launch  product_launch
41       2021-09-01                 NFIS-II Strategy Launch          policy
34       2022-08-01    Safaricom Ethiopia Commercial Launch    market_entry
35       2023-08-01                  M-Pesa Ethiopia Launch  product_launch
36       2024-01-01        Fayda Digital ID Program Rollout  infrastructure
37       2024-07-29         Foreign Exchange Liberalization          policy
38       2024-10-01     P2P Transaction Count Surpasses ATM       milestone
39       2025-10-27            M-Pesa EthSwitch Integration     partnership
42       2025-12-15       Safaricom Ethiopia Price Increase         pricing
40       2025-12-18  EthioPay Instant Payment System Launch  infrastructure

Insight 1

The dataset is primarily focused on the Access and Usage pillars, which aligns with the project's objective of forecasting account ownership and digital payment adoption.

Insight 2

Most records come from operator reports and nationally representative surveys, providing complementary supply-side and demand-side perspectives.

Insight 3

Approximately 93% of records have high confidence, indicating that the dataset is built largely from authoritative sources.

Insight 4

Indicator coverage is uneven. Core indicators such as account ownership have multiple observations, while many operational indicators (e.g., M-Pesa users and Telebirr transaction values) have only one observation. These sparse indicators will require enrichment before they can effectively support forecasting.

Insight 5

The event timeline captures major milestones in Ethiopia's digital finance ecosystem, including the launch of Telebirr, the entry of M-Pesa, the rollout of Fayda Digital ID, and payment infrastructure developments. These events provide a strong basis for later event-impact modeling.

In [19]:
df.groupby("record_type")["indicator_code"].unique()

record_type
event          [EVT_TELEBIRR, EVT_SAFARICOM, EVT_MPESA, EVT_F...
observation    [ACC_OWNERSHIP, ACC_MM_ACCOUNT, ACC_4G_COV, AC...
target                  [ACC_OWNERSHIP, ACC_FAYDA, GEN_MM_SHARE]
Name: indicator_code, dtype: object

In [20]:
import pandas as pd

# ----------------------------
# Internet Penetration Records
# Source: World Bank (IT.NET.USER.ZS)
# ----------------------------

internet_data = [
    ("2020", 16.1),
    ("2021", 16.7),
    ("2022", 18.0),
    ("2023", 20.3),
    ("2024", 21.9)
]

# Find the next available record number
last_id = (
    df["record_id"]
    .str.extract(r"REC_(\d+)")
    .astype(float)
    .max()[0]
)

next_id = int(last_id) + 1

new_records = []

for year, value in internet_data:

    new_records.append({

        "record_id": f"REC_{next_id:04d}",
        "record_type": "observation",
        "category": None,

        "pillar": "USAGE",

        "indicator": "Internet Penetration",

        "indicator_code": "USG_INTERNET_PEN",

        "indicator_direction": "higher_better",

        "value_numeric": value,

        "value_text": None,

        "value_type": "percentage",

        "unit": "%",

        "observation_date": f"{year}-12-31",

        "period_start": None,

        "period_end": None,

        "fiscal_year": year,

        "gender": "all",

        "location": "Ethiopia",

        "region": None,

        "source_name": "World Bank",

        "source_type": "research",

        "source_url": "https://data.worldbank.org/indicator/IT.NET.USER.ZS?locations=ET",

        "confidence": "high",

        "related_indicator": None,

        "relationship_type": None,

        "impact_direction": None,

        "impact_magnitude": None,

        "impact_estimate": None,

        "lag_months": None,

        "evidence_basis": None,

        "comparable_country": "",

        "collected_by": "mijuu",

        "collection_date": pd.Timestamp.today().strftime("%Y-%m-%d"),

        "original_text": f"Individuals using the Internet (% of population): {value}",

        "notes": (
            "Added during Task 1 enrichment. "
            "Internet penetration is a leading indicator of digital payment adoption."
        )

    })

    next_id += 1

# Convert to dataframe
internet_df = pd.DataFrame(new_records)

# Append
df = pd.concat([df, internet_df], ignore_index=True)

# Ensure datetime
df["observation_date"] = pd.to_datetime(df["observation_date"])

# Verify
print(df[df["indicator_code"]=="USG_INTERNET_PEN"])

print(f"\nDataset shape: {df.shape}")

   record_id  record_type category pillar             indicator  \
43  REC_0034  observation     None  USAGE  Internet Penetration
44  REC_0035  observation     None  USAGE  Internet Penetration
45  REC_0036  observation     None  USAGE  Internet Penetration
46  REC_0037  observation     None  USAGE  Internet Penetration
47  REC_0038  observation     None  USAGE  Internet Penetration

      indicator_code indicator_direction  value_numeric value_text  \
43  USG_INTERNET_PEN       higher_better           16.1       None
44  USG_INTERNET_PEN       higher_better           16.7       None
45  USG_INTERNET_PEN       higher_better           18.0       None
46  USG_INTERNET_PEN       higher_better           20.3       None
47  USG_INTERNET_PEN       higher_better           21.9       None

    value_type  ... impact_direction impact_magnitude impact_estimate  \
43  percentage  ...             None             None            None
44  percentage  ...             None             None            None
45  percentage  ...             None             None            None
46  percentage  ...             None             None            None
47  percentage  ...             None             None            None

   lag_months evidence_basis comparable_country collected_by collection_date  \
43       None           None                           mijuu      2026-07-22
44       None           None                           mijuu      2026-07-22
45       None           None                           mijuu      2026-07-22
46       None           None                           mijuu      2026-07-22
47       None           None                           mijuu      2026-07-22

                                        original_text  \
43  Individuals using the Internet (% of populatio...
44  Individuals using the Internet (% of populatio...
45  Individuals using the Internet (% of populatio...
46  Individuals using the Internet (% of populatio...
47  Individuals using the Internet (% of populatio...

                                                notes
43  Added during Task 1 enrichment. Internet penet...
44  Added during Task 1 enrichment. Internet penet...
45  Added during Task 1 enrichment. Internet penet...
46  Added during Task 1 enrichment. Internet penet...
47  Added during Task 1 enrichment. Internet penet...

[5 rows x 34 columns]

Dataset shape: (48, 34)

In [21]:
df.tail()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
43,REC_0034,observation,None,USAGE,Internet Penetration,USG_INTERNET_PEN,higher_better,16.1,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-22,Individuals using the Internet (% of populatio...,Added during Task 1 enrichment. Internet penet...
44,REC_0035,observation,None,USAGE,Internet Penetration,USG_INTERNET_PEN,higher_better,16.7,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-22,Individuals using the Internet (% of populatio...,Added during Task 1 enrichment. Internet penet...
45,REC_0036,observation,None,USAGE,Internet Penetration,USG_INTERNET_PEN,higher_better,18.0,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-22,Individuals using the Internet (% of populatio...,Added during Task 1 enrichment. Internet penet...
46,REC_0037,observation,None,USAGE,Internet Penetration,USG_INTERNET_PEN,higher_better,20.3,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-22,Individuals using the Internet (% of populatio...,Added during Task 1 enrichment. Internet penet...
47,REC_0038,observation,None,USAGE,Internet Penetration,USG_INTERNET_PEN,higher_better,21.9,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-22,Individuals using the Internet (% of populatio...,Added during Task 1 enrichment. Internet penet...

In [22]:
df.head()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
0,REC_0001,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,22.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Baseline year,NaN
1,REC_0002,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,35.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
2,REC_0003,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,46.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,NaN,NaN
3,REC_0004,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,56.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN
4,REC_0005,observation,NaN,ACCESS,Account Ownership Rate,ACC_OWNERSHIP,higher_better,36.0,NaN,percentage,...,NaN,NaN,NaN,NaN,NaN,Example_Trainee,2025-01-20,NaN,Gender disaggregated,NaN

In [23]:
# ---------------------------------------------
# Mobile Cellular Subscriptions
# World Bank Indicator: IT.CEL.SETS.P2
# ---------------------------------------------

mobile_data = [
    ("2020", 37.42),
    ("2021", 52.81),
    ("2022", 56.96),
    ("2023", 59.87),
    ("2024", 65.08)
]

# last_id = (
#     df["record_id"]
#       .str.extract(r"REC_(\d+)")
#       .astype(int)
#       .max()[0]
# )

next_id = 39

new_records = []

for year, value in mobile_data:

    new_records.append({

        "record_id": f"REC_{next_id:04d}",
        "record_type": "observation",
        "category": None,

        "pillar": "USAGE",

        "indicator": "Mobile Cellular Subscriptions",

        "indicator_code": "USG_MOBILE_SUB",

        "indicator_direction": "higher_better",

        "value_numeric": value,

        "value_text": None,

        "value_type": "percentage",

        "unit": "subscriptions per 100 people",

        "observation_date": f"{year}-12-31",

        "period_start": None,

        "period_end": None,

        "fiscal_year": year,

        "gender": "all",

        "location": "Ethiopia",

        "region": None,

        "source_name": "World Bank Open Data",

        "source_type": "research",

        "source_url": "https://data.worldbank.org/indicator/IT.CEL.SETS.P2?locations=ET",

        "confidence": "high",

        "related_indicator": None,

        "relationship_type": None,

        "impact_direction": None,

        "impact_magnitude": None,

        "impact_estimate": None,

        "lag_months": None,

        "evidence_basis": None,

        "comparable_country": "",

        "collected_by": "mijuu",

        "collection_date": "2026-07-21",

        "original_text":
            f"World Bank Indicator IT.CEL.SETS.P2: Mobile cellular subscriptions (per 100 people) = {value} ({year})",

        "notes":
            "Added during Task 1 enrichment. Mobile subscriptions are a leading indicator of digital financial service adoption."

    })

    next_id += 1

mobile_df = pd.DataFrame(new_records)

df = pd.concat([df, mobile_df], ignore_index=True)

print(df[df["indicator_code"]=="USG_MOBILE_SUB"])

   record_id  record_type category pillar                      indicator  \
48  REC_0039  observation     None  USAGE  Mobile Cellular Subscriptions
49  REC_0040  observation     None  USAGE  Mobile Cellular Subscriptions
50  REC_0041  observation     None  USAGE  Mobile Cellular Subscriptions
51  REC_0042  observation     None  USAGE  Mobile Cellular Subscriptions
52  REC_0043  observation     None  USAGE  Mobile Cellular Subscriptions

    indicator_code indicator_direction  value_numeric value_text  value_type  \
48  USG_MOBILE_SUB       higher_better          37.42       None  percentage
49  USG_MOBILE_SUB       higher_better          52.81       None  percentage
50  USG_MOBILE_SUB       higher_better          56.96       None  percentage
51  USG_MOBILE_SUB       higher_better          59.87       None  percentage
52  USG_MOBILE_SUB       higher_better          65.08       None  percentage

    ... impact_direction impact_magnitude impact_estimate lag_months  \
48  ...             None             None            None       None
49  ...             None             None            None       None
50  ...             None             None            None       None
51  ...             None             None            None       None
52  ...             None             None            None       None

   evidence_basis comparable_country collected_by collection_date  \
48           None                           mijuu      2026-07-21
49           None                           mijuu      2026-07-21
50           None                           mijuu      2026-07-21
51           None                           mijuu      2026-07-21
52           None                           mijuu      2026-07-21

                                        original_text  \
48  World Bank Indicator IT.CEL.SETS.P2: Mobile ce...
49  World Bank Indicator IT.CEL.SETS.P2: Mobile ce...
50  World Bank Indicator IT.CEL.SETS.P2: Mobile ce...
51  World Bank Indicator IT.CEL.SETS.P2: Mobile ce...
52  World Bank Indicator IT.CEL.SETS.P2: Mobile ce...

                                                notes
48  Added during Task 1 enrichment. Mobile subscri...
49  Added during Task 1 enrichment. Mobile subscri...
50  Added during Task 1 enrichment. Mobile subscri...
51  Added during Task 1 enrichment. Mobile subscri...
52  Added during Task 1 enrichment. Mobile subscri...

[5 rows x 34 columns]

In [24]:
df.tail()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
48,REC_0039,observation,None,USAGE,Mobile Cellular Subscriptions,USG_MOBILE_SUB,higher_better,37.42,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-21,World Bank Indicator IT.CEL.SETS.P2: Mobile ce...,Added during Task 1 enrichment. Mobile subscri...
49,REC_0040,observation,None,USAGE,Mobile Cellular Subscriptions,USG_MOBILE_SUB,higher_better,52.81,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-21,World Bank Indicator IT.CEL.SETS.P2: Mobile ce...,Added during Task 1 enrichment. Mobile subscri...
50,REC_0041,observation,None,USAGE,Mobile Cellular Subscriptions,USG_MOBILE_SUB,higher_better,56.96,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-21,World Bank Indicator IT.CEL.SETS.P2: Mobile ce...,Added during Task 1 enrichment. Mobile subscri...
51,REC_0042,observation,None,USAGE,Mobile Cellular Subscriptions,USG_MOBILE_SUB,higher_better,59.87,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-21,World Bank Indicator IT.CEL.SETS.P2: Mobile ce...,Added during Task 1 enrichment. Mobile subscri...
52,REC_0043,observation,None,USAGE,Mobile Cellular Subscriptions,USG_MOBILE_SUB,higher_better,65.08,None,percentage,...,None,None,None,None,None,,mijuu,2026-07-21,World Bank Indicator IT.CEL.SETS.P2: Mobile ce...,Added during Task 1 enrichment. Mobile subscri...

In [25]:
df["record_id"].values

<StringArray>
['REC_0001', 'REC_0002', 'REC_0003', 'REC_0004', 'REC_0005', 'REC_0006',
 'REC_0007', 'REC_0008', 'REC_0009', 'REC_0010', 'REC_0011', 'REC_0012',
 'REC_0013', 'REC_0014', 'REC_0015', 'REC_0016', 'REC_0017', 'REC_0018',
 'REC_0019', 'REC_0020', 'REC_0021', 'REC_0022', 'REC_0023', 'REC_0024',
 'REC_0025', 'REC_0026', 'REC_0027', 'REC_0028', 'REC_0029', 'REC_0030',
 'REC_0031', 'REC_0032', 'REC_0033', 'EVT_0001', 'EVT_0002', 'EVT_0003',
 'EVT_0004', 'EVT_0005', 'EVT_0006', 'EVT_0007', 'EVT_0008', 'EVT_0009',
 'EVT_0010', 'REC_0034', 'REC_0035', 'REC_0036', 'REC_0037', 'REC_0038',
 'REC_0039', 'REC_0040', 'REC_0041', 'REC_0042', 'REC_0043']
Length: 53, dtype: str

In [26]:
# ---------------------------------------------
# Mobile Money Agent Network
# Source: National Bank of Ethiopia
# ---------------------------------------------

agent_data = [
    ("2020", 22725),
    ("2021", 35964),
    ("2022", 156876),
    ("2023", 233036),
    ("2024", 415084)
]

next_id = 44

new_records = []

for year, value in agent_data:

    new_records.append({

        "record_id": f"REC_{next_id:04d}",

        "record_type": "observation",

        "category": None,

        "pillar": "USAGE",

        "indicator": "Mobile Money Agent Network",

        "indicator_code": "USG_AGENT_NETWORK",

        "indicator_direction": "higher_better",

        "value_numeric": value,

        "value_text": None,

        "value_type": "count",

        "unit": "agents",

        "observation_date": f"{year}-12-31",

        "period_start": None,

        "period_end": None,

        "fiscal_year": year,

        "gender": "all",

        "location": "Ethiopia",

        "region": None,

        "source_name": "National Bank of Ethiopia Financial Stability Report",

        "source_type": "regulator",

        "source_url": "https://www.nbe.gov.et/wp-content/uploads/2024/11/Financial-Stability-Report_NOV2024.pdf",

        "confidence": "high",

        "related_indicator": None,

        "relationship_type": None,

        "impact_direction": None,

        "impact_magnitude": None,

        "impact_estimate": None,

        "lag_months": None,

        "evidence_basis": None,

        "comparable_country": "",

        "collected_by": "mijuu",

        "collection_date": "2026-07-21",

        "original_text":
            f"NBE Financial Stability Report: Mobile Money Agents = {value:,} ({year})",

        "notes":
            "Added during Task 1 enrichment. Mobile money agent network size is a direct indicator of financial service access. Values are reported by NBE for fiscal years ending June and mapped to the corresponding calendar year."

    })

    next_id += 1

agent_df = pd.DataFrame(new_records)

df = pd.concat([df, agent_df], ignore_index=True)

# Verify
df[df["indicator_code"] == "USG_AGENT_NETWORK"]

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
53,REC_0044,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,22725.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
54,REC_0045,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,35964.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
55,REC_0046,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,156876.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
56,REC_0047,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,233036.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
57,REC_0048,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,415084.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...

In [27]:
df.tail()

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
53,REC_0044,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,22725.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
54,REC_0045,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,35964.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
55,REC_0046,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,156876.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
56,REC_0047,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,233036.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
57,REC_0048,observation,None,USAGE,Mobile Money Agent Network,USG_AGENT_NETWORK,higher_better,415084.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...

In [28]:
# ---------------------------------------------
# Mobile Money Accounts
# Source: National Bank of Ethiopia
# ---------------------------------------------

mm_accounts = [
    ("2020", 15103804),
    ("2021", 39359653),
    ("2022", 60822659),
    ("2023", 90176046),
    ("2024", 107523560)
]

next_id = 49

new_records = []

for year, value in mm_accounts:

    new_records.append({

        "record_id": f"REC_{next_id:04d}",

        "record_type": "observation",

        "category": None,

        "pillar": "USAGE",

        "indicator": "Mobile Money Accounts",

        "indicator_code": "USG_MM_ACCOUNTS",

        "indicator_direction": "higher_better",

        "value_numeric": value,

        "value_text": None,

        "value_type": "count",

        "unit": "accounts",

        "observation_date": f"{year}-12-31",

        "period_start": None,

        "period_end": None,

        "fiscal_year": year,

        "gender": "all",

        "location": "Ethiopia",

        "region": None,

        "source_name": "National Bank of Ethiopia Financial Stability Report",

        "source_type": "regulator",

        "source_url": "https://www.nbe.gov.et/wp-content/uploads/2024/11/Financial-Stability-Report_NOV2024.pdf",

        "confidence": "high",

        "related_indicator": None,

        "relationship_type": None,

        "impact_direction": None,

        "impact_magnitude": None,

        "impact_estimate": None,

        "lag_months": None,

        "evidence_basis": None,

        "comparable_country": "",

        "collected_by": "mijuu",

        "collection_date": "2026-07-21",

        "original_text":
            f"NBE Financial Stability Report: Mobile Money Accounts = {value:,} ({year})",

        "notes":
            "Added during Task 1 enrichment. Mobile money accounts are a direct indicator of digital financial inclusion. Values are reported by NBE for fiscal years ending June and mapped to the corresponding calendar year."

    })

    next_id += 1

mm_df = pd.DataFrame(new_records)

df = pd.concat([df, mm_df], ignore_index=True)

# Verify
df[df["indicator_code"] == "USG_MM_ACCOUNTS"]

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
58,REC_0049,observation,None,USAGE,Mobile Money Accounts,USG_MM_ACCOUNTS,higher_better,15103804.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
59,REC_0050,observation,None,USAGE,Mobile Money Accounts,USG_MM_ACCOUNTS,higher_better,39359653.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
60,REC_0051,observation,None,USAGE,Mobile Money Accounts,USG_MM_ACCOUNTS,higher_better,60822659.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
61,REC_0052,observation,None,USAGE,Mobile Money Accounts,USG_MM_ACCOUNTS,higher_better,90176046.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...
62,REC_0053,observation,None,USAGE,Mobile Money Accounts,USG_MM_ACCOUNTS,higher_better,107523560.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Financial Stability Report: Mobile Money A...,Added during Task 1 enrichment. Mobile money a...

In [29]:
# ---------------------------------------------
# Commercial Bank Branch Network
# Source: National Bank of Ethiopia
# ---------------------------------------------

branch_data = [
    ("2020", 6511),
    ("2021", 7571),
    ("2022", 8944),
    ("2023", 11281),
    ("2024", 12725)
]

next_id = 54

new_records = []

for year, value in branch_data:

    new_records.append({

        "record_id": f"REC_{next_id:04d}",

        "record_type": "observation",

        "category": None,

        "pillar": "ACCESS",

        "indicator": "Commercial Bank Branches",

        "indicator_code": "ACC_BANK_BRANCHES",

        "indicator_direction": "higher_better",

        "value_numeric": value,

        "value_text": None,

        "value_type": "count",

        "unit": "branches",

        "observation_date": f"{year}-12-31",

        "period_start": None,

        "period_end": None,

        "fiscal_year": year,

        "gender": "all",

        "location": "Ethiopia",

        "region": None,

        "source_name": "National Bank of Ethiopia Annual Report",

        "source_type": "regulator",

        "source_url": "https://nbe.gov.et/publications-statistics/statistics/annual-report/",

        "confidence": "high",

        "related_indicator": None,

        "relationship_type": None,

        "impact_direction": None,

        "impact_magnitude": None,

        "impact_estimate": None,

        "lag_months": None,

        "evidence_basis": None,

        "comparable_country": "",

        "collected_by": "mijuu",

        "collection_date": "2026-07-21",

        "original_text":
            f"NBE Annual Report: Commercial bank branches = {value:,} ({year})",

        "notes":
            "Added during Task 1 enrichment. Commercial bank branch network is a direct indicator of physical access to financial services. Values are reported by NBE for fiscal years ending June and mapped to the corresponding calendar year."

    })

    next_id += 1

branch_df = pd.DataFrame(new_records)

df = pd.concat([df, branch_df], ignore_index=True)

# Verify
df[df["indicator_code"] == "ACC_BANK_BRANCHES"]

,record_id,record_type,category,pillar,indicator,indicator_code,indicator_direction,value_numeric,value_text,value_type,...,impact_direction,impact_magnitude,impact_estimate,lag_months,evidence_basis,comparable_country,collected_by,collection_date,original_text,notes
63,REC_0054,observation,None,ACCESS,Commercial Bank Branches,ACC_BANK_BRANCHES,higher_better,6511.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Annual Report: Commercial bank branches = ...,Added during Task 1 enrichment. Commercial ban...
64,REC_0055,observation,None,ACCESS,Commercial Bank Branches,ACC_BANK_BRANCHES,higher_better,7571.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Annual Report: Commercial bank branches = ...,Added during Task 1 enrichment. Commercial ban...
65,REC_0056,observation,None,ACCESS,Commercial Bank Branches,ACC_BANK_BRANCHES,higher_better,8944.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Annual Report: Commercial bank branches = ...,Added during Task 1 enrichment. Commercial ban...
66,REC_0057,observation,None,ACCESS,Commercial Bank Branches,ACC_BANK_BRANCHES,higher_better,11281.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Annual Report: Commercial bank branches = ...,Added during Task 1 enrichment. Commercial ban...
67,REC_0058,observation,None,ACCESS,Commercial Bank Branches,ACC_BANK_BRANCHES,higher_better,12725.0,None,count,...,None,None,None,None,None,,mijuu,2026-07-21,NBE Annual Report: Commercial bank branches = ...,Added during Task 1 enrichment. Commercial ban...

In [30]:
os.makedirs("../data/enriched", exist_ok=True)

df.to_csv("../data/enriched/ethiopia_fi_enriched.csv", index=False)

print("enriched dataset saved successfully")

enriched dataset saved successfully

In [32]:
# New indicator codes to add to reference_codes

new_reference_codes = pd.DataFrame([
    {
        "field": "indicator_code",
        "code": "USG_INTERNET_PEN",
        "description": "Internet Penetration (% of population using the Internet)",
        "applies_to": "observation"
    },
    {
        "field": "indicator_code",
        "code": "USG_MOBILE_SUB",
        "description": "Mobile Cellular Subscriptions (per 100 people)",
        "applies_to": "observation"
    },
    {
        "field": "indicator_code",
        "code": "USG_AGENT_NETWORK",
        "description": "Mobile Money Agent Network Size",
        "applies_to": "observation"
    },
    {
        "field": "indicator_code",
        "code": "USG_MM_ACCOUNTS",
        "description": "Registered Mobile Money Accounts",
        "applies_to": "observation"
    },
    {
        "field": "indicator_code",
        "code": "ACC_BANK_BRANCHES",
        "description": "Commercial Bank Branches",
        "applies_to": "observation"
    }
])

# Append to existing reference_codes
reference_codes = pd.concat(
    [ref_df, new_reference_codes],
    ignore_index=True
)

# Remove duplicates (in case you run the cell twice)
reference_codes = reference_codes.drop_duplicates(
    subset=["field", "code"],
    keep="first"
).reset_index(drop=True)

# Verify the new entries
reference_codes[
    reference_codes["field"] == "indicator_code"
].tail(10)

,field,code,description,applies_to
71,indicator_code,USG_INTERNET_PEN,Internet Penetration (% of population using th...,observation
72,indicator_code,USG_MOBILE_SUB,Mobile Cellular Subscriptions (per 100 people),observation
73,indicator_code,USG_AGENT_NETWORK,Mobile Money Agent Network Size,observation
74,indicator_code,USG_MM_ACCOUNTS,Registered Mobile Money Accounts,observation
75,indicator_code,ACC_BANK_BRANCHES,Commercial Bank Branches,observation

In [33]:
reference_codes.to_csv(
    "../data/enriched/reference_codes_updated.csv",
    index=False
)

print("Updated reference codes saved successfully!")

Updated reference codes saved successfully!